package memory_disk;

import java.util.Iterator;

/**
 * Generate a series of page references.
 * 
 * 
 * 
 * @author Ben
 *
 */
public interface PageReferenceGenerator extends Iterable<Integer>,
		Iterator<Integer> {

	/**
	 * Starting at current, find the page that will be referenced least soon and
	 * return its number.
	 * 
	 * @return Page number that will be used least soon.
	 */
	int oracle();

	/**
	 * Return the number of references that will be generated by this generator.
	 * 
	 */
	int getNumberOfReferences();

	/**
	 * Get the number of pages in the process space.
	 */
	int getNumberOfPages();

}
